### ISSUE TITLE
Request new ACV1's key

### ISSUE THREAD

**Issue by Cosetto** [Forlos/vn_re#3]
The game is [this](https://vndb.org/v29057) and also the [side story](https://vndb.org/v32165)

**Comment by Dir-A** [comment]
我が姫君に栄冠を PKG | Waga Himegimi ni Eikan o PKG | 0x3793B711
我が姫君に栄冠を 将軍の誘惑 DL | Waga Himegimi ni Eikan o: Shogun no Yuuwaku DL | 0x309F2F1D

**Comment by Cosetto** [comment]
Can I ask how did you check game name and its key? It said first 4 byte of crc64 of game name but I'm confused

**Comment by Cosetto** [comment]
I also need the key of English release of [this game](https://vndb.org/v28834) too

**Comment by Dir-A** [comment]
I'm not quite sure about this engine.
a friend asked me about it yesterday so I saw your question.

The script file key for this engine is usually the name of the game.
The game name will be input a function and a key will be returned.

How to find this function?
Very simple, just search for the string "script/0.txt" or "script/1.txt"
Find the one where the assembly instruction starts with push
The push instruction is immediately followed by a call that is.

This function handles not only the unpacking key, but also the filename

Example:
string filename = "ハナヒメ＊アブソリュート！"  --in--> funcation --out---> 0x30bc61c8

If you want to get the name of the file you can hook this function and output its input parameters.
![QQ截图20221009135906](https://user-images.githubusercontent.com/79064817/194741022-db6570d4-57e9-4b52-8056-1aab7f1111d5.png)
![SC2OP~NM4E2I4Y05(08_VTA](https://user-images.githubusercontent.com/79064817/194741026-6414e06b-9477-4ed7-8c56-aafde8a1477e.png)

For the new version
我が姫君に栄冠を A little different.
You can still get the filename from this function.
But you may not be able to get the script.dat key.
I think it's possible that the compiler has iinline the function

So What should we do?

Now we need to find where to read the script.dat
It's easy to just search for string "script.dat"
You should only find one place assemblies starting with mov.

set breakpoint at the end of the loop algorithm cmp dword ptr ds:[0x0186E2D4], 0x0
F9->F8 Run to the position shown.
Then switch the dump window to address mode,
Go to address 0x0186D024 (mov dword ptr ds:[0x0186D024], 0x1)
The value of 0x0186D024 is 0x1 and the next is the key.
There may be times when the next one is a zero and the next one is the key
![QQ截图20221009140610](https://user-images.githubusercontent.com/79064817/194741045-2c9c84e8-c24d-428d-95d3-67228cbd81de.png)
![QQ截图20221009140849](https://user-images.githubusercontent.com/79064817/194741195-97f9706a-2041-4829-8c4f-5e960192502b.png)

Honey*Honey*Honey I only have the Chinese version. Find the key in the same way as above.
Honey*Honey*Honey CN | Honey*Honey*Honey CN | 0x5B3699E4

**Comment by Cosetto** [comment]
Can you make an example video, I'm quite lost at finding the string

**Comment by Dir-A** [comment]
Video Here ->[2022-10-09 15-10-32.7z.zip](https://github.com/Forlos/vn_re/files/9740958/2022-10-09.15-10-32.7z.zip)
rename to 2022-10-09 15-10-32.7z use 7z extract it

**Comment by Cosetto** [comment]
Thanks so much bro

**Comment by Cosetto** [comment]
Btw bro, do you know how to use the create_hash_list.py and merge_name_lists.py in vn_re/tools to generate file name? I think that's not how we get the file name

**Comment by Dir-A** [comment]
Oh, I haven't written much python.So I don't really understand.

ACV1 engine filenames are encrypted，You only can get a string of hash in pack。(like new version KRKRZ)

create_hash_list.py :dump all the hash filename in pack。you can get a hash_list.txt file。

crc_name_check.py :check hash_list.txt(filename encrypted) then output name_list.txt(filename Decrypted),
But you need to provide the file name for the program to calculate first.

merge_name_lists.py :Splicing multiple hash_list.txt files and sorted

To parse all the files, you need to first get the filename through hook game related functions.

**Comment by Cosetto** [comment]
Ah, so this is just like another version of new wamsoft krkrz. Oh yeah, there's another [acv1 tool](https://github.com/vn-tools/whale-tools/tree/master/hash_finder) for finding hash written in c++

**Comment by Cosetto** [comment]
Bro, you think you can make this just like cmvs? Hook dump out the images and read without repack? There's [an old hook for acv1](https://github.com/Inori/FuckGalEngine/tree/master/Minato/MinatoKit/MinatoPatch) which I guess can help the engine read utf16

**Comment by Dir-A** [comment]
Reading utf16 is not difficult.
But the game's script code encoding cannot be changed it may crash, and the pushstr function has strict internal encoding checks。

This engine exports a function called loadfile Hook this function can read files without pack.
Search for the script string to find the function to load text file,Hook this function can replace text without repack script.dat

But I think the engine itself should be able to read unpacked files，If I have time, I will try to find it.

**Comment by Cosetto** [comment]
Thanks bro.

**Comment by Cosetto** [comment]
I think I'm good with the script. I just need the hook to read files is arcx.dat

**Comment by Dir-A** [comment]
OK bro, I'm almost done, I'll publish it tonight。read file without repack（Except script.dat）

**Comment by Cosetto** [comment]
thanks so much bro
